[project]
name = "main"
version = "0.1.0"
description = "TODO"
readme = "../README.md"
requires-python = ">= 3.11"

[dependencies]
python = "^3.11"
hydra-core = "^1.3"
legible = { path = "../legible", develop = true }
OFTEN-DeepRL = { path = "../OFTEN-DeepRL", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
