[tool.poetry]
name = "main"
version = "0.1.0"
description = "TODO"
readme = "../README.md"
authors = ["Marit"]

[tool.poetry.dependencies]
python = "^3.11"
hydra-core = "^1.3"
legible = { path = "../legible", develop = true }
oftendeeprl = { path = "../OFTEN-DeepRL", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



