env:
  name: BerkeleyPacman-v0
  level: smallClassic
  
training:
  steps_initial: 750_000
  steps_norm: 750_000
  algorithm: dqn
  ng_margin: 50
  norm_violation_filtering: True
  feature_extractor: complete

rules:
  episodes: 600
  steps: 2500_000
  nr_features: 63
  lime_test_size: 100
  compute_correlation: False
  feature_extractor: extended-8
  model_number: 
  shield_number:
  updates:
    episodes: 5 
    data_collection_episodes: 150
    prune_interval: 100
    add_rule_variations: False
    prune_rules: False


asp:
  horizon: 3
  radius: 5

eval:
  episodes: 3000

defaults:
  - norm: vegetarian
