env:
  name: BerkeleyPacman-v0
  level: smallClassic
  
training:
  steps_initial: 1000_000
  steps_norm: 1000_000
  algorithm: dqn
  ng_margin: 50
  norm_violation_filtering: True
  feature_extractor: complete

rules:
  episodes: 600
  steps: 2500_000
  nr_features: 62
  lime_test_size: 100
  compute_correlation: False
  feature_extractor: extended-8
  model_number: 
  shield_number:
  exclude_features_in_neg_rules: [0,1,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,32,33,39,40,41,42,52,53,54,55,56,57,58,59,60,61] # ONLY VEG RIGHT NOW
  features_with_enumerable_values: [6,7]
asp:
  horizon: 2
  radius: 5

norms: [vegetarian]